### PR TITLE
Restructuring; USBasp support; Arduino Mega1280 and Mega2560 support

### PR DESCRIPTION
**Pull request by matthijs-oosterhoff**
Hi,

I tried to use your CMake template for Arduino, bit it didn’t work out of the box. The first problem was that the CMake template assumes the user has installed the necessary compilers and tools, which I haven't. But they are provided with the Arduino installation, so I figured it would be better to use those instead.
Second problem were the Arduino source includes. They didn’t match with the files included in my Arduino 1.6.7 installation, so I updated those.

While at it, I added support for flashing with a USBasp programmer, and default configurations for Arduino Mega1280 and Mega2560.

Oh, and I renamed some files and folders… I hope you don’t mind :)

### CODE REVIEW

**Comment by Reobos** [comment]
Hey I just noticed this pull request. I made a few changes myself in another pull request. I think both sets of changes compliment each other and can be merged. 
Note that I've also already incorporated some of these changes into my own repo based on this one if you want to have a look at my profile.

**Comment by tmpsantos** [comment]
@matthijs-oosterhoff hey, for some reason I didn't get notified about PRs at this repo, do you still want to merge it?

**Comment by tmpsantos** [comment]
And sorry about the delay, apparently I "unwatched" my own repo by accident.

**Comment by matthijs-oosterhoff** [comment]
When I found out about the fork @maxbader made, I sort of abandoned my fork... His is far more elaborate. But thanks anyway for starting this project, it helped me a lot with Arduino development using CMake 👍

**Comment by tmpsantos** [comment]
@matthijs-oosterhoff indeed, I will deprecate this one and point to his tree, thank you.

**Pull request closed without merging**
